#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $GHOULS_REPO == "ghoulsbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $GHOULS_REPO == "GHOULSBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $GHOULS_REPO =~ $regex ]]
    then
        if [[ $GHOULS_REPO_BRANCH ]]
        then
            echo "${GHOULS_REPO}/archive/${GHOULS_REPO_BRANCH}.zip"
        else
            echo "${GHOULS_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="ghoulsbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    GHOULSTH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $GHOULSPATH
    echo "    Starting GhoulsBot    "
    echo "
                            ____ _   _  ___  _   _ _     ____  ____   ___ _____ 

 / ___| | | |/ _ \| | | | |   / ___|| __ ) / _ \_   _|

| |  _| |_| | | | | | | | |   \___ \|  _ \| | | || |  

| |_| |  _  | |_| | |_| | |___ ___) | |_) | |_| || |  

 \____|_| |_|\___/ \___/|_____|____/|____/ \___/ |_|
                          
                          
                          
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
